### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by Vince-cheng** [Vince-cheng/itoken#2]
##### 安装命令
````
sudo curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
````

##### docker-compse 部署 gitlab
```
version: '3'
services:
    web:
      image: 'twang2218/gitlab-ce-zh:10.5'
      restart: always
      hostname: '192.168.79.140'
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://192.168.79.140'
          gitlab_rails['gitlab_shell_ssh_port'] = 2222
          unicorn['port'] = 8888
          nginx['listen_port'] = 80
      ports:
        - '80:80'
        - '8443:443'
        - '2222:22'
      volumes:
        - /usr/local/docker/gitlab/config:/etc/gitlab
        - /usr/local/docker/gitlab/data:/var/opt/gitlab
        - /usr/local/docker/gitlab/logs:/var/log/gitlab
```

##### docker-compose 部署 nexus
```
version: '3.1'
services:
  nexus:
    restart: always
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - 8081:8081
    volumes:
      - /usr/local/docker/nexus/data:/nexus-data
```

###### 前提：在github上下载最新离线安装版 上传到虚拟机
```
tar -zxvf harbor-offline-installer-v1.8.0.tgz
# 输出如下
harbor/harbor.v1.8.0.tar.gz
harbor/prepare
harbor/LICENSE
harbor/install.sh
harbor/harbor.yml
```

###### 修改配置文件
```
vi harbor.yml
# 修改为域名或你服务器 IP
hostname: 192.168.79.140
```

##### 验证安装是否成功

>通过浏览器访问 http://192.168.79.140 ，看到登录页面

>输入账号 admin，密码 Harbor12345，登录成功后

###### 配置客户端

>在 /etc/docker/daemon.json 中增加如下内容（如果文件不存在请新建该文件）
```{
  "registry-mirrors": [
    "https://registry.docker-cn.com"
  ],
  "insecure-registries": [
    "192.168.79.140"
  ]
}
```

````
# 在项目中标记镜像
docker tag nginx 192.168.79.140/myshop/nginx:latest
# 登录 Harbor
docker login 192.168.79.140 -u admin -p Harbor12345
# 推送镜像到项目
docker push 192.168.79.140/myshop/nginx:latest
```

```
在其它机器下载镜像只需要配置好客户端即可
docker pull 192.168.79.140/myshop/nginx:latest
```
